version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      copilotkit:
        patterns:
          - "@copilotkit/*"
    reviewers:
      - "jpr5"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types:
          - minor
          - patch
      major:
        patterns: ["*"]
        update-types:
          - major
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
