import * as path from "node:path";
import type {
  CopilotKitProviderLocation,
  CopilotKitProps,
  ProviderChainEntry,
  UnserializableRef,
} from "../types";
import { toImportSpecifier } from "./import-specifier";

export interface RenderEntryOptions {
  provider: CopilotKitProviderLocation;
  ancestors: ProviderChainEntry[];
  /** Specifier used to import the HooksAggregator. */
  aggregatorModule: string;
  /** Absolute directory where the generated entry.tsx will be written. */
  outDir: string;
  /** Overrides the user's runtimeUrl in the emitted <CopilotKitProvider>. */
  runtimeUrlOverride?: string;
}

/**
 * Emits the playground entry module. Imports every ancestor provider using
 * the real import source resolved from the user's file, plus CopilotKit(Provider)
 * itself from the user's package, and renders the reconstructed chain wrapping
 * HooksAggregator.
 *
 * Exports two components:
 * - `PlaygroundEntry` — the provider chain wrapping HooksAggregator only.
 *   Used by the MountedComponentsPanel to show user components in isolation.
 * - `ChatPlayground` — the same provider chain wrapping both HooksAggregator
 *   AND CopilotChat. Because both are resolved inside the same bundle module
 *   instance (forwarding-stubs → real v2), React context flows correctly and
 *   the chat connects to the spawned runtime.
 *
 * Ancestors with no resolvable import source (locally declared in the user's
 * file) are skipped with a comment — the wrapper is omitted rather than
 * generating broken code.
 */
export function renderEntry(opts: RenderEntryOptions): string {
  const { provider, ancestors, aggregatorModule, outDir } = opts;

  const lines: string[] = [
    "/* @generated by src/extension/playground/codegen. Do not edit. */",
    // We replaced @copilotkit/react-core/v2's <CopilotChat /> with our own
    // <PlaygroundChat /> (emitted as a sibling source file). Long story
    // short: CopilotChat's onSubmitInput silently failed to fire runAgent
    // inside the playground bundle and the cause was buried in subscription
    // / license / state-machine code we don't ship. PlaygroundChat drives
    // the runtime directly via copilotkit.runAgent + useRenderToolCall, so
    // the user's tool render components still appear inline.
    'import * as React from "react";',
    `import { HooksAggregator } from ${JSON.stringify(aggregatorModule)};`,
    `import { ${provider.importedName} } from ${JSON.stringify(
      provider.importSource,
    )};`,
    `import { PlaygroundChat } from "./playground-chat";`,
  ];

  // Emit per-ancestor imports using the user's real import specifier.
  // Ancestors we can't resolve (locally declared, not exported) are skipped
  // with a comment — render falls through as if the wrapper was omitted.
  interface Renderable {
    ancestor: ProviderChainEntry;
    /** Local identifier used inside the generated JSX. */
    localName: string;
  }
  const renderables: Renderable[] = [];
  const skipped: ProviderChainEntry[] = [];
  const usedNames = new Set<string>([
    "HooksAggregator",
    "React",
    provider.importedName,
    "PlaygroundChat",
  ]);

  for (const a of ancestors) {
    // Lowercased tag names are HTML elements (<div>, <span>) — not providers.
    if (!/^[A-Z]/.test(a.tagName)) continue;
    if (a.importSource == null || a.importedName == null) {
      skipped.push(a);
      continue;
    }

    // Dedupe local name against imports already in scope.
    let local = a.tagName;
    let suffix = 2;
    while (usedNames.has(local)) {
      local = `${a.tagName}_${suffix++}`;
    }
    usedNames.add(local);

    const specifier = rewriteImportSpecifier(
      a.importSource,
      a.filePath,
      outDir,
    );
    if (a.isDefaultImport) {
      lines.push(`import ${local} from ${JSON.stringify(specifier)};`);
    } else if (a.importedName === a.tagName) {
      lines.push(
        `import { ${a.tagName}${
          local !== a.tagName ? ` as ${local}` : ""
        } } from ${JSON.stringify(specifier)};`,
      );
    } else {
      // User wrote `import { X as Y }` — reproduce the alias.
      lines.push(
        `import { ${a.importedName} as ${local} } from ${JSON.stringify(
          specifier,
        )};`,
      );
    }

    renderables.push({ ancestor: a, localName: local });
  }

  lines.push("");

  const playgroundEntry = renderProviderChain(
    opts,
    renderables,
    skipped,
    "<HooksAggregator />",
    "PlaygroundEntry",
  );

  // Inside ChatPlayground the HooksAggregator exists only to register the
  // user's CopilotKit hooks (useCopilotAction, useFrontendTool, etc.) so
  // PlaygroundChat can see them via the same registry. The components'
  // actual return values ("v1 actions", "WeatherRadar", …) are visual
  // noise we don't want in the chat surface — the right-side
  // MountedComponentsPanel lists them separately from the scan result.
  // Wrap in `display: none` so hooks still fire but the JSX they return
  // is hidden. Error boundaries inside MountCard keep recording mount
  // errors to `window.__copilotkit_playground_errors`.
  const chatPlayground = renderProviderChain(
    opts,
    renderables,
    skipped,
    `<div style={{ display: "none" }} aria-hidden="true">\n          <HooksAggregator />\n        </div>\n        <PlaygroundChat />`,
    "ChatPlayground",
  );

  return (
    lines.join("\n") + "\n" + playgroundEntry + "\n" + chatPlayground + "\n"
  );
}

/**
 * Builds the JSX body for a single named export that wraps the given children
 * string inside the reconstructed provider chain.
 */
function renderProviderChain(
  opts: RenderEntryOptions,
  renderables: Array<{ ancestor: ProviderChainEntry; localName: string }>,
  skipped: ProviderChainEntry[],
  childrenJsx: string,
  exportName: string,
): string {
  const { provider } = opts;
  const fnLines: string[] = [];

  fnLines.push(`export function ${exportName}(): React.ReactElement {`);
  fnLines.push("  return (");

  const closeTags: string[] = [];
  let indent = "    ";

  for (const s of skipped) {
    fnLines.push(
      `${indent}{/* skipped ancestor: ${s.tagName} (locally declared in ${
        s.filePath
      }, not exported) */}`,
    );
  }

  for (const { ancestor, localName } of renderables) {
    const props = renderProps(ancestor.props);
    fnLines.push(`${indent}<${localName}${props}>`);
    closeTags.push(`</${localName}>`);
    indent += "  ";
  }

  const effectiveProps: CopilotKitProps = opts.runtimeUrlOverride
    ? { ...provider.props, runtimeUrl: opts.runtimeUrlOverride }
    : provider.props;
  const providerProps = renderProps(effectiveProps);
  fnLines.push(`${indent}<${provider.importedName}${providerProps}>`);
  indent += "  ";
  // Indent each line of the children block.
  for (const childLine of childrenJsx.split("\n")) {
    fnLines.push(`${indent}${childLine}`);
  }
  indent = indent.slice(2);
  fnLines.push(`${indent}</${provider.importedName}>`);

  for (let i = closeTags.length - 1; i >= 0; i--) {
    indent = indent.slice(2);
    fnLines.push(`${indent}${closeTags[i]}`);
  }

  fnLines.push("  );");
  fnLines.push("}");
  fnLines.push("");

  return fnLines.join("\n");
}

/**
 * Resolves the user's import specifier into something valid from outDir.
 * - Non-relative specifiers (npm packages, scoped packages) pass through.
 * - Relative specifiers are resolved against the importer's directory and
 *   re-expressed relative to outDir via toImportSpecifier.
 */
function rewriteImportSpecifier(
  userSpecifier: string,
  importerFilePath: string,
  outDir: string,
): string {
  if (!userSpecifier.startsWith(".")) return userSpecifier;
  const absolute = path.resolve(path.dirname(importerFilePath), userSpecifier);
  return toImportSpecifier(outDir, absolute);
}

function renderProps(props: CopilotKitProps): string {
  const parts: string[] = [];
  for (const [name, value] of Object.entries(props)) {
    if (name === "__spread") continue; // skip: spread captured as unserializable
    if (name === "children") continue; // JSX element wraps its own children
    parts.push(" " + renderProp(name, value));
  }
  return parts.join("");
}

/**
 * Recursively renders a value for embedding in a JSX expression slot.
 * Walks objects and arrays so that nested UnserializableRef values are
 * inlined as their `.source` expression instead of being JSON.stringified
 * as metadata objects. Returns false if the tree contains no UnserializableRef
 * nodes, allowing the caller to fall back to JSON.stringify for compact output.
 */
function renderValue(value: unknown): string | false {
  if (isUnserializable(value)) {
    return value.source;
  }
  if (value === null || value === undefined) return false;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return false;
  }
  if (Array.isArray(value)) {
    let hasUnserializable = false;
    const parts: string[] = [];
    for (const v of value) {
      const rendered = renderValue(v);
      if (rendered !== false) {
        hasUnserializable = true;
        parts.push(rendered);
      } else {
        parts.push(JSON.stringify(v));
      }
    }
    return hasUnserializable ? `[${parts.join(",")}]` : false;
  }
  if (typeof value === "object") {
    let hasUnserializable = false;
    const parts: string[] = [];
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      const rendered = renderValue(v);
      if (rendered !== false) {
        hasUnserializable = true;
        parts.push(`${JSON.stringify(k)}:${rendered}`);
      } else {
        parts.push(`${JSON.stringify(k)}:${JSON.stringify(v)}`);
      }
    }
    return hasUnserializable ? `{${parts.join(",")}}` : false;
  }
  return false;
}

function renderProp(
  name: string,
  value:
    | string
    | number
    | boolean
    | null
    | CopilotKitProps
    | CopilotKitProps[]
    | UnserializableRef,
): string {
  if (isUnserializable(value)) {
    return `${name}={${value.source}}`;
  }
  if (value === null) return `${name}={null}`;
  if (typeof value === "string") return `${name}=${JSON.stringify(value)}`;
  if (typeof value === "number" || typeof value === "boolean") {
    return `${name}={${JSON.stringify(value)}}`;
  }
  // Object or array — recursively render so nested UnserializableRef values
  // are inlined as source expressions instead of serialized as metadata.
  // If renderValue returns false (no unserializables found), fall back to
  // JSON.stringify for compact output identical to the previous behavior.
  const rendered = renderValue(value);
  return `${name}={${rendered !== false ? rendered : JSON.stringify(value)}}`;
}

function isUnserializable(v: unknown): v is UnserializableRef {
  return (
    typeof v === "object" &&
    v !== null &&
    "__unserializable" in v &&
    (v as { __unserializable: unknown }).__unserializable === true
  );
}

